
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sessions-starter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8181
#Если необходимо изменить как часто очищаются сессии
#session:
#  cleanup:
#    enabled: false
#    frequency: "0 * * * * ?" # Каждую минуту